---
name: _loading
description: Load required parameters for the subsequent jobs

on:
  workflow_call:
    inputs:
      build_options_file:
        description: The file containing build options
        required: false
        type: string
        default: 'ci/build_options.txt'

      event_name:
        required: false
        type: string
        description: Optional event name to use for building
        default: ${{ github.event_name }}

      pr_ref:
        required: false
        type: string
        description: Optional pull request reference to use for building
        default: ${{ github.event.pull_request.head.ref }}

      pr_repo:
        required: false
        type: string
        description: Optional pull request repository to use for building
        default: ${{ github.event.pull_request.head.repo.full_name }}

      base_ref:
        required: false
        type: string
        description: Optional base reference to use for building
        default: ${{ github.ref_name }}

    outputs:
      build_args:
        description: The build arguments
        value: ${{ jobs.loading.outputs.build_args }}

jobs:
  loading:
    runs-on: ubuntu-latest
    outputs:
      build_args: ${{ steps.loading.outputs.build_args }}
    steps:
      - name: Sync Codebase
        id: sync
        uses: AudioReach/audioreach-workflows/.github/actions/sync@master
        with:
          event_name: ${{ inputs.event_name }}
          pr_ref: ${{ inputs.pr_ref }}
          pr_repo: ${{ inputs.pr_repo }}
          base_ref: ${{ inputs.base_ref }}

      - name: Load Parameters
        id: loading
        uses: AudioReach/audioreach-workflows/.github/actions/loading@master
        with:
          build_options_file: ${{ inputs.build_options_file }}
